logging:
  level:
    root: INFO
    oidc: DEBUG
    org.springframework.session: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: INFO
    org.springframework.data: INFO

cron:
  node-cron-job-responsible: true
  token-cleaner-expression: "0 0/15 * * * *"
  key-rollover-expression: "0 0/15 * * * *"
  consent-expiry-duration-days: 90

server:
  max-http-header-size: 10000000
  tomcat:
    max-http-post-size: 10000000
    max-http-form-post-size: 10000000
    max-swallow-size: 10000000
    max-connections: 20


# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

mongodb_db: oidc_test
oidc_saml_mapping_path: classpath:/oidc/saml_mapping.json
openid_configuration_path: classpath:/openid-configuration.json
secret_key_set_path: classpath:/secret_keyset.json
associated_data: 4CEFFA8B-90DD-4737-8B04-6DA51C5B29AE
access_token_one_way_hash_salt: secret
private_key_path: classpath:/id_rsa
certificate_path: classpath:/id_rsa.pub
default_acr_value: http://test.surfconext.nl/assurance/loa1
secure_cookie: false
oidc_token_endpoint: http://localhost:8080/oidc/token

features:
  # Do we enforce that the RS - if eduID pseudonymisation is required - belongs to the SURF IdP linked to the eduID user account?
  # We link RS's and SURF IdP's using the coin:institution-guid
  enforce-eduid-resource-server-linked-account: true
  # Do we enforce that the scopes granted to an access_token are configured with the RS?
  enforce-scope-resource-server: true

idp:
  alias: engine-test
  # comma separated string of metadata url's
  metadata_urls: https://engine.test2.surfconext.nl/authentication/idp/metadata
  name_id: https://engine.test2.surfconext.nl/authentication/idp/metadata
  metadata_signing_certificate_path: classpath:/engine.test2.surfconext.nl.pem

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/${mongodb_db}
  thymeleaf:
    cache: false
  security:
    saml2:
      network:
        read-timeout: 10000
        connect-timeout: 5000
      service-provider:
        entity-id: https://org.openconext.oidc.ng
        prefix: oidc
        alias: oidc-proxy
        base-path: http://localhost:8080
        sign-metadata: true
        sign-requests: true
        want-assertions-signed: true
        single-logout-enabled: false
        name-ids:
          - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
          - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified

manage:
  user: oidcng
  password: secret

token-api:
  # Is the token API enabled for Profile and eduID? If not access to the token API endpoints is forbidden
  enabled: true
  users:
    - user: eduid
      password: secret
    - user: profile
      password: secret

eduid:
  user: oidcng
  password: secret
  uri: https://eduid.test2.surfconext.nl/myconext/api/attribute-manipulation
  enabled: true

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
    info:
      enabled: true
      show-details: when_authorized
