logging:
  level:
    root: INFO
    oidc: DEBUG
    org.springframework.session: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: INFO
    org.springframework.data: INFO

cron:
  node-cron-job-responsible: true
  token-cleaner-expression: "0 0/15 * * * *"
  key-rollover-expression: "0 0/15 * * * *"

server:
  max-http-header-size: 10000000
  tomcat:
    max-http-post-size: 10000000

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

mongodb_db: oidc_test
oidc_saml_mapping__path: classpath:/oidc/saml_mapping.json
openid_configuration_path: classpath:/openid-configuration.json
secret_key_set_path: classpath:/secret_keyset.json
associated_data: 4CEFFA8B-90DD-4737-8B04-6DA51C5B29AE
private_key_path: classpath:/id_rsa
certificate_path: classpath:/id_rsa.pub
default_acr_value: http://test.surfconext.nl/assurance/loa1
secure_cookie: false

idp:
  alias: engine-test
  # comma separated string of metadata url's
  metadata_urls: https://engine.test2.surfconext.nl/authentication/idp/metadata
  name_id: https://engine.test2.surfconext.nl/authentication/idp/metadata
  certificate_url: https://engine.test2.surfconext.nl/authentication/idp/certificate

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/${mongodb_db}
  thymeleaf:
    cache: false
  security:
    saml2:
      network:
        read-timeout: 10000
        connect-timeout: 5000
      service-provider:
        entity-id: https://org.openconext.oidc.ng
        prefix: oidc
        alias: oidc-proxy
        base-path: http://localhost:8080
        sign-metadata: true
        sign-requests: true
        want-assertions-signed: true
        single-logout-enabled: false
        name-ids:
          - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
          - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified

manage:
  user: manage
  password: secret

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
    info:
      enabled: true
      show-details: when_authorized
